### ISSUE TITLE
Installer fails at database creation

### ISSUE THREAD

**Issue by steve-lad** [chan-sccp/sccp_manager#12]
chan-sccp/chan-sccp#572

**Comment by steve-lad** [comment]
The Stable branch will not fix errors in the user configuration.

The Develop branch should do this. The install error that you are seeing is caused by the fact that FreePbx Doctrine cannot parse correctly the files that it creates (unfortunately)

The Doctrine output has been corrected in the latest Develop branch (it may take some time for GitHub to propagate it to the snapshot).

Please try again in a few hours and confirm that this has been fixed.

**Comment by vaDrn** [comment]
Got same error during install. Link I used https://github.com/chan-sccp/sccp_manager/archive/refs/heads/develop.zip

![image](https://user-images.githubusercontent.com/48777021/121755804-3b7ebc00-cb6c-11eb-9e46-c2e4a7b2c521.png)

**Comment by steve-lad** [comment]
The error is not the same but the result is.
Please paste the exact contents of the exception in the top left box - the command looks good

**Comment by steve-lad** [comment]
@vaDrn In module admin, before trying to install this module, check for FreePBX module updates for your already installed modules, and apply any that are found

**Comment by vaDrn** [comment]
updated all FreePBX modules. Still error during install

Text of the exception:
`
An exception occurred while executing 'CREATE TABLE sccpbuttonconfig (ref VARCHAR(15) DEFAULT '' NOT NULL, reftype VARCHAR(15) DEFAULT 'sccpdevice' NOT NULL, instance TINYINT(1) DEFAULT '0' NOT NULL, buttontype VARCHAR(255) DEFAULT 'line' NOT NULL, name VARCHAR(36) DEFAULT NULL, options VARCHAR(100) DEFAULT NULL, INDEX ref (ref, reftype), PRIMARY KEY(ref, reftype, instance, buttontype)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
`

**Comment by steve-lad** [comment]
@vaDrn That command executes perfectly on Mariadb - what database are you using?

Are you familiar with accessing the database directly? If so can you run

SHOW TABLE STATUS WHERE NAME LIKE 'sccp%';

and paste the output here

I think that the issue is that you have run the mysql-enum as indicated in the old wiki instructions. This step is no longer necessary and in fact creates problems like this.

**Comment by vaDrn** [comment]
It's database that goes preinstalled on FreePBX iso. I thought it was mariadb. Here is the version command output:
![image](https://user-images.githubusercontent.com/48777021/121776868-3e68c380-cbe3-11eb-997d-a9b67fb01622.png)

here is the table status output:
![image](https://user-images.githubusercontent.com/48777021/121776932-a9b29580-cbe3-11eb-8d75-5dc1c72103da.png)

I followed this instructions: `https://github.com/chan-sccp/chan-sccp/wiki/FreePBX_SCCP-modules` it was last updated 7 days ago.
I can reinstall everything from scratch and skip `mysql -p asterisk < /usr/src/chan-sccp/conf/mysql-v5_enum.sql` part. Shouldn't take too long.

**Comment by vaDrn** [comment]
so no any sccp tables.
![image](https://user-images.githubusercontent.com/48777021/121777189-e763ee00-cbe4-11eb-9168-6b615dde0cef.png)

still got error during install
```
An exception occurred while executing 'CREATE TABLE sccpbuttonconfig (ref VARCHAR(15) DEFAULT '' NOT NULL, reftype VARCHAR(15) DEFAULT 'sccpdevice' NOT NULL, instance TINYINT(1) DEFAULT '0' NOT NULL, buttontype VARCHAR(255) DEFAULT 'line' NOT NULL, name VARCHAR(36) DEFAULT NULL, options VARCHAR(100) DEFAULT NULL, INDEX ref (ref, reftype), PRIMARY KEY(ref, reftype, instance, buttontype)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

**Comment by steve-lad** [comment]
@vaDrn No need - there are no conflicts in your tables. I have a fix (I think), but would really like to understand why this is failing on your machine and not on any others

can you do an 

apt-get update;
apt-get upgrade;

(or the equivalent on your machine)
to see if there are any update packages for MariaDb

**Comment by vaDrn** [comment]
FreePBX based on CentOS I think.  `yum update` `yum upgrade` was the fist thing I made.

![image](https://user-images.githubusercontent.com/48777021/121777576-006d9e80-cbe7-11eb-9817-75fbc113ac7a.png)

tried to install `stable` one again, no errors during install. Table status command output:
![image](https://user-images.githubusercontent.com/48777021/121777382-d798d980-cbe5-11eb-966e-f0b3ba69e118.png)

no realtime config tho
![image](https://user-images.githubusercontent.com/48777021/121777495-7f160c00-cbe6-11eb-9b7b-6ced5351ad32.png)

**Comment by steve-lad** [comment]
@vaDrn There is an error in your database now, and it will prove fatal at some stage. You are mixing encodings in the view.

Can you do the following.

Uninstall and remove Stable
Download and install Develop (until it hangs)

In the database, run

SHOW TABLE STATUS WHERE NAME LIKE 'sccp%';

and paste the output again.

**Comment by vaDrn** [comment]
i'm not mixing anything - it's created purely by `stabe` release installation.
I removed `stable` release and installed `develop` one. No error during install. Here is the status output:
![image](https://user-images.githubusercontent.com/48777021/121777834-28a9cd00-cbe8-11eb-8f56-15f63fba6fac.png)

also sccp module info: 
![image](https://user-images.githubusercontent.com/48777021/121777863-50993080-cbe8-11eb-8595-592340f0afd1.png)

**Comment by vaDrn** [comment]
![image](https://user-images.githubusercontent.com/48777021/121777979-de751b80-cbe8-11eb-8d52-b994dc01c955.png)

yep, fatal it is

**Comment by steve-lad** [comment]
@vaDrn Are you using CENTOS 5 or 7?

**Comment by vaDrn** [comment]
It's 7...?
![image](https://user-images.githubusercontent.com/48777021/121778063-43307600-cbe9-11eb-84c6-216f5e5966cf.png)

**Comment by vaDrn** [comment]
hmm
![image](https://user-images.githubusercontent.com/48777021/121778094-6ce99d00-cbe9-11eb-8e64-8c89e6939bcb.png)

**Comment by steve-lad** [comment]
@vaDrn OK Lets fix this. You need to update MariaDb and I will show you how to.

Logout and close FreePBX window

rm -r /var/www/html/admin/modules/sccp_manager/

run this in the Database

Drop table sccpbuttonconfig; drop table sccpuser; drop view sccpdeviceconfig;

Let me know when done

**Comment by vaDrn** [comment]
done
only sccpdevice, sccpdevmodel, sccpline and sccpsettings tables left

**Comment by steve-lad** [comment]
cd /etc/yum.repos.d/

using your favourite editor create a file called MariaDB.repo

and paste the following into it:

```
# MariaDB 10.5 CentOS repository list - created 2021-06-12 13:57 UTC
# http://downloads.mariadb.org/mariadb/repositories/
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/10.5/centos7-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1
```

Save the file

let me know when done

**Comment by vaDrn** [comment]
done

**Comment by steve-lad** [comment]
yum install MariaDB-server MariaDB-client

**Comment by vaDrn** [comment]
done

**Comment by vaDrn** [comment]
got error from firewall `Firewall was unable to connect to MySQL after 30 seconds.`

**Comment by steve-lad** [comment]
mysql -V

**Comment by vaDrn** [comment]
now it's spams it constantly

**Comment by vaDrn** [comment]
`mysql  Ver 15.1 Distrib 10.5.10-MariaDB, for Linux (x86_64) using readline 5.1`

**Comment by steve-lad** [comment]
Firewall messages stopped?

**Comment by vaDrn** [comment]
nope. still going

**Comment by steve-lad** [comment]
dirty but a reboot is probably required

**Comment by vaDrn** [comment]
it's dead after reboot
![image](https://user-images.githubusercontent.com/48777021/121779190-880adb80-cbee-11eb-960a-320ab4d0ed2f.png)

**Comment by vaDrn** [comment]
bunch of errors after mariadb startup
![image](https://user-images.githubusercontent.com/48777021/121779217-c7392c80-cbee-11eb-9135-6e902e69076b.png)

**Comment by steve-lad** [comment]
Have you tried running mysql_upgrade?

**Comment by vaDrn** [comment]
after mysql_upgrade 
![image](https://user-images.githubusercontent.com/48777021/121779653-dd47ec80-cbf0-11eb-9a55-c134339870fa.png)

**Comment by steve-lad** [comment]
Does FreePBX load?

**Comment by vaDrn** [comment]
nope. FreePBX won't load. MariaDB and asterisk won't start after reload. I can start them manually after `systemctl daemon-reload` command. FreePBX won't run at all

**Comment by steve-lad** [comment]
Are you on a VM?

**Comment by vaDrn** [comment]
yes. I have snapshots before db update

**Comment by steve-lad** [comment]
So ---- rollback. Sorry but FreePBX are !!!! about their distros. Keep a snapshot of the present though and I will look into it more

**Comment by steve-lad** [comment]
Once you have done, let me know what tables you have for sccp

**Comment by vaDrn** [comment]
sorry, I was wrong. I only have snapshots before sccp manager installs. So there are no sccp tables in db.

**Comment by steve-lad** [comment]
No pb

Download Develop and install (wait for the error)

**Comment by steve-lad** [comment]
Sorry - do not install

**Comment by steve-lad** [comment]
cd /var/www/html/admin/modules/sccp_manager

**Comment by vaDrn** [comment]
done

**Comment by steve-lad** [comment]
OK I think that I have seen the issue

In your favourite editor, edit module.xml and go to line 128

**Comment by vaDrn** [comment]
done

**Comment by vaDrn** [comment]
`<field name="buttontype" type="string" default="line" primarykey="true"/>`

**Comment by steve-lad** [comment]
change to

```
 <field name="buttontype" type="string" length="192" default="line" primarykey="true"/>
```

and save

**Comment by vaDrn** [comment]
done

**Comment by steve-lad** [comment]
Now try running install

**Comment by vaDrn** [comment]
error:
`
An exception occurred while executing 'CREATE TABLE sccpbuttonconfig (ref VARCHAR(15) DEFAULT '' NOT NULL, reftype VARCHAR(15) DEFAULT 'sccpdevice' NOT NULL, instance TINYINT(1) DEFAULT '0' NOT NULL, buttontype VARCHAR(192) DEFAULT 'line' NOT NULL, name VARCHAR(36) DEFAULT NULL, options VARCHAR(100) DEFAULT NULL, INDEX ref (ref, reftype), PRIMARY KEY(ref, reftype, instance, buttontype)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
`

**Comment by steve-lad** [comment]
Edit the file again and change the length from 192 to 150

**Comment by steve-lad** [comment]
and try install ... again

**Comment by vaDrn** [comment]
installed with no errors
tables:
![image](https://user-images.githubusercontent.com/48777021/121780773-f2734a00-cbf5-11eb-9b77-df9d1a6e7801.png)

and sccp info:
![image](https://user-images.githubusercontent.com/48777021/121780800-0ae36480-cbf6-11eb-9931-1c0542b4f3e9.png)

**Comment by steve-lad** [comment]
OK looks good. 

As you are a maso, uninstall Sccp manager, and change the length again to 190, and then reinstall

**Comment by vaDrn** [comment]
this is new 
![image](https://user-images.githubusercontent.com/48777021/121780944-ad9be300-cbf6-11eb-962b-15dab5a2c198.png)

**Comment by vaDrn** [comment]
it shows as uninstalled anyway

**Comment by steve-lad** [comment]
No sweat - thats normal.

Wait a sec please

**Comment by vaDrn** [comment]
![Uploading image.png…]()

**Comment by vaDrn** [comment]
![image](https://user-images.githubusercontent.com/48777021/121781006-f8b5f600-cbf6-11eb-8f75-3e97ef090267.png)

**Comment by steve-lad** [comment]
You are too fast

Uninstall again please

**Comment by steve-lad** [comment]
That was my mistake btw

**Comment by vaDrn** [comment]
uninstalled. length set to 190

**Comment by steve-lad** [comment]
now in db
```
drop table sccpdevice;drop table sccpuser;drop table sccpbuttonconfig;drop table sccpline;drop view sccpdeviceconfig;
```

**Comment by steve-lad** [comment]
and then install

**Comment by vaDrn** [comment]
it still working. we have to do something about it
![image](https://user-images.githubusercontent.com/48777021/121781161-97daed80-cbf7-11eb-9251-cd0cfe017e8a.png)

**Comment by vaDrn** [comment]
update mariadb or something

**Comment by steve-lad** [comment]
You have a very old version of MariaDb - an indexed field that can be NULL has a max length of 190

**Comment by steve-lad** [comment]
But you are probably not alone with these distros, so I will look at the impact of changing the length.

In the meantime, try again to update MariaDB but FIRST, uninstall MariaDB, then add the repo, and install. That may work better

**Comment by steve-lad** [comment]
Thanks for your patience and excellent feedback

**Comment by steve-lad** [comment]
Comment here if you succeed in updating MariaDB

... and now, get some sleep!

**Comment by vaDrn** [comment]
Aye Aye

**Comment by steve-lad** [comment]
and finally, you can revert to stable at any time as the tables have been created, and your extconfig is correct.

What is in extconfig.conf, as the installer has updated extconfig.custom.conf?

**Comment by vaDrn** [comment]
yep. custom one is updated:
![image](https://user-images.githubusercontent.com/48777021/121781532-5b0ff600-cbf9-11eb-97e6-f187f6186cee.png)

**Comment by steve-lad** [comment]
but what is in the base?

**Comment by vaDrn** [comment]
![image](https://user-images.githubusercontent.com/48777021/121781567-809cff80-cbf9-11eb-9369-882c3962ae6e.png)

**Comment by steve-lad** [comment]
Are you joking?

**Comment by steve-lad** [comment]
Sorry what is in /etc/extconfig.conf?

**Comment by vaDrn** [comment]
mah bad. got it wrong - base one is empty 
![image](https://user-images.githubusercontent.com/48777021/121781644-e7221d80-cbf9-11eb-8620-618ef8adc51b.png)

**Comment by steve-lad** [comment]
So:
```
cp /etc/asterisk/extconfig.custom.conf /etc/asterisk/extconfig.conf
rm /etc/asterisk/extconfig.custom.conf
```
and you are clean

**Comment by steve-lad** [comment]
And please, tomorrow, close this issue. It is the db at fault and not sccp_manager

**Comment by vaDrn** [comment]
Trying to add sccp extension 
![image](https://user-images.githubusercontent.com/48777021/121781852-d0c89180-cbfa-11eb-8897-43420bfdffab.png)

**Comment by vaDrn** [comment]
if i try to add it again i've got an error that this number is already taken. `realtime load sccpline id 1` return nothing

**Comment by steve-lad** [comment]
Create a new issue - this is Develop, but I am really concerned that it is related to the age of your install

This is the first time that I have seen this!!

**Comment by steve-lad** [comment]
Ahh you are adding extensions via Extensions and not via add Phone. Create a new issue and I will look at it

**Comment by vaDrn** [comment]
welp. it's official distro from freepbx.org. Even wiki says to download from there

**Comment by vaDrn** [comment]
anyway. **HUGE** thanks for your time. I'll make other issue ticket tomorrow

**Comment by steve-lad** [comment]
@vaDrn Could you please let me know which FreePBX distro you installed?

**Comment by vaDrn** [comment]
default one on freepbx download page `https://www.freepbx.org/downloads/`. sng7-pbx-64bit-2104-1. release date: April 2021
