### ISSUE TITLE
FreePBX "Quick create extension" error on creation of new sccp line

### ISSUE THREAD

**Issue by vaDrn** [chan-sccp/sccp_manager#15]
adding sccp extension through "Quick create extension" window fails with error:
![image](https://user-images.githubusercontent.com/48777021/121792309-5ffb9680-cc47-11eb-9015-76e12eb200e5.png)

In mysql sccpline table there will be no new lines.

Addition of new extensions works properly through `sccp manager` UI

**Comment by steve-lad** [comment]
@vaDrn This has been fixed in current Develop. Download Develop as in the wiki (module admin does not work at present due to FreePBX issue; patch proposed to FreePBX)

**Comment by vaDrn** [comment]
just to be sure: i need to uninstall sccp manager, remove it and then redownload it as in wiki install instructions?

will this work:
```
cd /var/www/html/admin/modules/
rm -rf /sccp_manager
git clone https://github.com/chan-sccp/sccp_manager.git
fwconsole chown
```
so that I can update it through

```
git fetch
git pull
```

**Comment by steve-lad** [comment]
If you use git, you will break future functionality, and you will not be forced to use the installer. As you have seen, the installer is important.

Do not use uninstall - you will lose data!

Just  redownload using module admin, install.
