### ISSUE TITLE
Missing SCCP tab in Extension edit page

### ISSUE THREAD

**Issue by vaDrn** [chan-sccp/sccp_manager#20]
There is missing `SCCP` tab on the Extension edit page, as well as on the page for creating a new extension SCCP.
This tab allows you to configure additional line options, as well as used codecs for a specific device.

how it looks on version from this git:
![image](https://user-images.githubusercontent.com/48777021/122636732-e1b75c80-d13e-11eb-8ed5-eb2269ea359e.png)

how it should be (version from PhantomVl git):
![image](https://user-images.githubusercontent.com/48777021/122637189-660adf00-d141-11eb-821c-1e6546022008.png)

sccp manager version: 14.2.0.10
FreePBX version: 15.0.17.34
Asterisk version: 16.17.0

SCCP Info page:
![image](https://user-images.githubusercontent.com/48777021/122637616-cbf86600-d143-11eb-8e89-8831a428106e.png)

**Comment by steve-lad** [comment]
Thanks to @vaDrn for reporting this issue, and for helping in its resolution
