### ISSUE TITLE
Hotline / Auto Provision support

### ISSUE THREAD

**Issue by dkgroot** [chan-sccp/sccp_manager#29]
When you enable "hotline" in 'SCCP Server Settings':'SCCP Device' chan-sccp will allow unknown devices to register to chan-sccp and will automatically assign them a so called 'Hotline' / PLAR (Private Line Automatic Ringdown) extension . This is a somewhat insecure setting for production environments but very nice when you are setting up a new environment with a large number of phones.

I noticed how these Hotline devices are able to connect and already show up in the 'Phone Manager':'SCCP Phone' list, with their Device Identifier, Type, Description: `*NEW*` and Status (So all the information we need is already there). But when you go to the config page for this device, the information is lost along the way.

![image](https://user-images.githubusercontent.com/1935794/126876302-2c3e1d31-39b4-458d-9ca3-cc7b6f4d1e33.png)

Enhancement: When you select the edit/config action button at the end, that it would transfer this knowledge and already fill in the type of the phone and it's Device ID, so the whole procedure could be reduced to setting up the line button for it. It could even move you to the second tab immediately asking for the line to assign right away.

On the  'SCCP Server Settings':'SCCP Device' page we ought to make the user aware this is insecure and should be switched of before going into production. A PLAR phone is still able to ring any other extension by entering the number on the phone before going off-hook. So either setup a secure context for these types of phones or switch off hotline.

**Comment by waffle-stomper** [comment]
@dkgroot - I think this was added in 5bfa3bc9309564076ddc4999dda3664e74e69543

**Comment by steve-lad** [comment]
Closing this issue. The suggested functionality has been added, and now the info section and the devices tab have additional warnings. 
@dkgroot Given the potential risk, why is the chan-sccp default enabled?
