### ISSUE TITLE
could not install sccp_manager

### ISSUE THREAD

**Issue by xfn2020** [chan-sccp/sccp_manager#31]
Ubuntu 20.04. asterisk 16 freepbx 15. chan-sccp compiled, installed and installed by given instruction. But can't install sccp_manager, getting a message:

Installing sccp_manager
Updating tables sccpdevice, sccpline, sccpbuttonconfig, sccpdevmodel, sccpuser, sccpsettings...Done
Checking for required Sccp_manager database tables..
Checking Asterisk Version :
Sccp model Compatible code :

Chan Sccp not Found. Install it before continuing ! 

What's wrong? How explain/point to sccp_manager installation that chan_sccp module succefully installed?

**Comment by steve-lad** [comment]
This is not an sccp_manager issue. Asterisk has not been set up correctly for RealTime and does not see chan-sccp. Either extconfig.conf or res_mysql_conf.conf are incorrect (or both) but most probably the first as freepbx should take care of the second
