### ISSUE TITLE
md5sum did not match

### ISSUE THREAD

**Issue by torowi** [chan-sccp/sccp_manager#36]
Hi,
while upgrading from 14.2.0.1 to 14.2.0.3 via Module Admin I got following error:

Downloading and Installing sccp_manager
Downloading sccp_manager 0 of 143 (0%)
Error(s) downloading sccp_manager:

    File Integrity failed for /var/www/html/admin/modules/_cache/v14.2.0.3.tar.gz - aborting (md5sum did not match)

**Comment by steve-lad** [comment]
This is a bug with FreePbx pending resolution. A patch has been submitted. 

FreePbx use a put instead of a get and GitHub baulks, hence the checksum error.

Upgrading to 14.3 will stop module admin trying to download a new version, as no higher versions are available
