### ISSUE TITLE
FreePBX wants to downgrade v14.3.0.13 to v14.2.0.1

### ISSUE THREAD

**Issue by waffle-stomper** [chan-sccp/sccp_manager#38]
I think the issue might be the version numbers in https://github.com/chan-sccp/sccp_manager/blob/develop/sccpManagerUpdater.json on lines 5 and 18:

https://github.com/chan-sccp/sccp_manager/blob/2b90440df7816697b16b29e17a2c70e2827809e3/sccpManagerUpdater.json#L5

https://github.com/chan-sccp/sccp_manager/blob/2b90440df7816697b16b29e17a2c70e2827809e3/sccpManagerUpdater.json#L18

**Comment by FrozenHaxor** [comment]
I keep having an issue with this also, every week when automatic updater runs, module performs a downgrade and breaks the system.

**Comment by steve-lad** [comment]
Could you please post a capture of module admin for sccp_manager - I do not see this issue

**Comment by waffle-stomper** [comment]
![sccp_manager_downgrade](https://user-images.githubusercontent.com/5958168/147419350-33f66722-708d-4106-9ca2-2b1919d3400c.png)

**Comment by steve-lad** [comment]
Thanks for the capture. Module admin appears to be working correctly as the user has to force a downgrade which normally one would not do.

Automatic update clearly has a bug that is implementing the downgrade when freepbx knows that it has the latest version.

However this also appears to confirm that the online upgrade freepbx bug is fixed, and so I will now update the online version. Check later today and see if version 14.3.0.15 is proposed, and can be successfully updated.

**Comment by waffle-stomper** [comment]
Thanks for looking into this!

> Check later today and see if version 14.3.0.15 is proposed, and can be successfully updated.

The good news is that I'm now offered the latest version (14.3.0.16). Unfortunately when I try to upgrade via the web UI, I get the following error:

```
Error(s) downloading sccp_manager:

    File Integrity failed for /var/www/html/admin/modules/_cache/v14.3.0.16.tar.gz - aborting (md5sum did not match)
```

Interestingly, upgrading from the command line (fwconsole ma upgrade sccp_manager) was successful.

After the upgrade, the Module Admin page no longer offers to downgrade the module, but the status is 'Enabled; Not available online'.

![Module-admin-not-available-online.png](https://user-images.githubusercontent.com/5958168/147507435-2abed7de-fb7f-42ea-8864-1ab77ff3dc0a.png)

**Comment by steve-lad** [comment]
The File integrity error bug is in freepbx - it has been reported but no progress as yet. They had already fixed part of this issue previously, and I guess that is why the upgrade via fwconsole works (different entry point).

The not available online is because in the trial image, the version is 14.3.0.15 but is labelled as 14.3.0.16.

This also explains why the automatic update worked (incorrectly) for FrozenHaxor! Automatic updater should no longer force a downgrade, but is clearly dangerous!

**Comment by steve-lad** [comment]
Closing this issue as it is a freepbx issue.
