### ISSUE TITLE
SCCP Manager throws an exception on a fresh install if you choose the wrong menu item

### ISSUE THREAD

**Issue by waffle-stomper** [chan-sccp/sccp_manager#39]
### Steps to reproduce:

1. Install the [FreePBX 16 distro](https://downloads.freepbxdistro.org/ISO/SNG7-PBX16-64bit-2109-3.iso)
2. Install Chan SCCP
3. Install SCCP Manager from the command line
`fwconsole ma downloadinstall https://github.com/chan-sccp/sccp_manager/archive/refs/tags/14.3.0.13.zip` 
4. In the FreePBX web UI, go to Sccp Connectivity > System Parameters

This throws the following exception because masterFilesStructure.xml is missing:

```
Whoops\Exception\ErrorException thrown with message "simplexml_load_file(): I/O warning : failed to load external entity &quot;/tftpboot/masterFilesStructure.xml&quot;"

Stacktrace:
#5 Whoops\Exception\ErrorException in /var/www/html/admin/modules/sccp_manager/views/advserver.model.php:155
#4 simplexml_load_file in /var/www/html/admin/modules/sccp_manager/views/advserver.model.php:155
#3 include in /var/www/html/admin/modules/sccp_manager/Sccp_manager.class.php:372
#2 FreePBX\modules\Sccp_manager:processPageData in /var/www/html/admin/modules/sccp_manager/Sccp_manager.class.php:295
#1 FreePBX\modules\Sccp_manager:advServerShowPage in /var/www/html/admin/modules/sccp_manager/page.sccp_adv.php:19
#0 include in /var/www/html/admin/config.php:647
```

### Workaround:
Before going to Sccp Connectivity > System Parameters, go to Sccp Connectivity > Server Config first.
This generates the required files. 

### Suggested fix:
Download https://github.com/dkgroot/provision_sccp/blob/master/tools/tftpbootFiles.xml and put it in /tftpboot/masterFilesStructure.xml during install (if possible)

### Alternate fix:

I'm bad at PHP and not very familiar with the project, so I haven't submitted a pull request, but could it be as simple as replacing this:

https://github.com/chan-sccp/sccp_manager/blob/2b90440df7816697b16b29e17a2c70e2827809e3/views/advserver.model.php#L155

With something like this:

https://github.com/chan-sccp/sccp_manager/blob/2b90440df7816697b16b29e17a2c70e2827809e3/Sccp_manager.class.php#L624-L630

**Comment by steve-lad** [comment]
Fixed in 14.3.0.15 (current develop)
