### ISSUE TITLE
Failure during SCCP Manager Install, cannot find chan-sccp

### ISSUE THREAD

**Issue by tclela20** [chan-sccp/sccp_manager#40]
Hello,

I am attempting to install the Chan SCCP manager into an Asterisk/FreePBX system. The system is online, and the chan_sccp module is loaded. I have done the following:

      - [X] Built and Installed chan_sccp
      - [X] Setup the SCCP contents of /etc/asterisk
      - [X] Loaded firmware and xml files to /tftpboot
      - [X] Followed the instructions for setting up the realtime database
      - [X] Verified the tables exist
      - [X] verified the data in /etc/asterisk/extconfig.conf
      - [X] verified the data in /etc/asterisk/res_config_mysql.conf
      - [X] Manually added and removed data from the device and line tables

Phones are provisioning via SCCP, but I cannot manage the lines via the FreePBX GUI. After all of these attempts I am still greeted with the error below. If someone could point me in the right direction to get this running I would be very appreciative.

![image](https://user-images.githubusercontent.com/70184188/146830148-1dd53de2-09f9-4fc6-aeb2-350ddf72ad26.png)

Asterisk: 16.21.1
DB: MariaDB 10.3.31
PHP: 7.0.1
SCCP: Latest from Repo Releases
SCCP Manager: 14.2

**Comment by steve-lad** [comment]
This is most probably an issue with the realtime config. Upgrade to version 14.3.0.13 which will fix any realtime config issues.

Closing as this is not an sccp_manager issue.
