### ISSUE TITLE
Vendor config settings not set in cnf file

### ISSUE THREAD

**Issue by steve-lad** [chan-sccp/sccp_manager#42]
Reported by @FrozenHaxor

It seems that the generated CNF files do not reflect the vendor config correctly, I changed the phone display timeout settings and saved them, then generated new CNF files and it populated the variables with default values anyway
 
 
Plus there is a naming duplication

![](https://files.gitter.im/5c346716d73408ce4fb3f89b/Rzyi/obraz.png)

![](https://files.gitter.im/5c346716d73408ce4fb3f89b/KyAq/obraz.png)

**Comment by FrozenHaxor** [comment]
Yes, forgot to enter the issue, sorry. I confirm this, and upon manually editing the CNF file the phones accepted the settings properly. Changing the phone settings from web panel resets the variables to default in the CNF file again ignoring user input in the context boxes.

**Comment by steve-lad** [comment]
Issue should be closed in version 14.3.0.18
