### ISSUE TITLE
sccp_manager fails to install

### ISSUE THREAD

**Issue by samam9911** [chan-sccp/sccp_manager#55]
I just installed the freepbx 15 distro with asterisk 18. I did yum update and also updated all modules then installed chan-sccp succefully. When I was trying to install sccp-mangaer i faced 2 issues:
1. the command mysql -u root asterisk < /usr/src/chan-sccp/conf/mysql-v5_enum.sql fails to create buttonconfig table due to foreign key constraint error (unable to create the foreign key on buttonconfig(device) to reference sccpdevice (name) the primary key and both have same data type!
2. when downloading the module into module admin and try to install the sccp-manager module i get the error:
3. PHP Parse error:  syntax error, unexpected 'class' (T_CLASS) in /var/www/html/admin/modules/sccp_manager/install.php on line 32
Whoops\Exception\ErrorException: syntax error, unexpected 'class' (T_CLASS) in file /var/www/html/admin/modules/sccp_manager/install.php on line 32
Stack trace:
  1. Whoops\Exception\ErrorException->() /var/www/html/admin/modules/sccp_manager/install.php:32
It seems to be a PHP issue since the distro comes with php56w. 
Is there a workaround? if not, which distro  freepbx/asterisk this supposed to work with. I am setting up freepbx mainly to use to manage 60 cisco 7960 phones. It's extremely important for me to get this working rather than installing sip on cisco phones.
Thanks for all the efforts on this project!

**Comment by steve-lad** [comment]
The first step is not required and no longer in the WiKi

The WiKi clearly indicates that 14.3.0.x requires PHP 7

You should use FreePbx 16 or use the prior version of sccp_manager indicated in the WiKi, noting that there are many resolved issues in this release that will not be fixed as FreePbx 16 is GA.

**Comment by samam9911** [comment]
Thanks for the reply! The distro version does not allow upgrading to PHP 7 that's why I was asking which freepbx/asterisk/sccp-manager work together.

**Comment by samam9911** [comment]
I installed the previous version 14.2 and it worked, thanks! If I upgrade to freePBX 16 will I hit the same PHP issue? in other words to get sccp-manager to work with freepbx 16, I have to use a different flavor of linux that supports PHP?

**Comment by steve-lad** [comment]
Read the WiKi which links to the ReadMe! FreePbx 16 requires PHP > 7.4. 

This normally has nothing to do with the linux flavour!

Install the FreePbx 16 distro, as you are starting from scratch, and you will (should) not have any issues IF you follow the wiki which means do not run the enum script in the db - the Sccp_Manager installer will do everything

**Comment by samam9911** [comment]
I upgraded to freepbx 16 distro and got the latest version of sccp-manager. Thanks a lot. wish it had a bulk load, it would have come so handy
