### ISSUE TITLE
The button function in DeviceButtons cannot be removed.

### ISSUE THREAD

**Issue by sq8mvy** [chan-sccp/sccp_manager#59]
sccp_manager version: 14.3.0.30
FreePBX 16

You cannot remove a button function in DeviceButtons - set it to empty or change the function type. After saving the settings, the buttons still have their previous functions assigned to them.
Adding and saving functions to empty buttons works fine.

**Comment by steve-lad** [comment]
Thanks for reporting this. It is confirmed as an issue and will be treated

**Comment by steve-lad** [comment]
In v14.4.0.5 this has been fixed. Additionally, buttons can be added in any order. Update via module admin
