### ISSUE TITLE
After module update, some settings are reset to defaults

### ISSUE THREAD

**Issue by ghost** [chan-sccp/sccp_manager#63]
FreePBX 16.0.10.50
When upgrading to version 14.5.0.4, some settings change to default
![2-Config-Device](https://user-images.githubusercontent.com/98538479/151635442-c117e2e3-04eb-4581-86e1-b71ab66c4570.png)
![3-Config-Advanced](https://user-images.githubusercontent.com/98538479/151635449-3d3c672b-add5-43d1-a29f-1b1d37192735.png)

**Comment by steve-lad** [comment]
Thanks for this well prepared issue. This has been identified and addressed, and will be fixed in the next release.
