### ISSUE TITLE
The hardware device drops the line association when the associated line is edited (and saved)

### ISSUE THREAD

**Issue by ghost** [chan-sccp/sccp_manager#65]
If you change and save the line (Extension), and then apply the FREEPBX settings, then this associated line with SCCP Phone will disappear from this device in the Phone Manager item
Every time you need to add this line on the device
![EditLine](https://user-images.githubusercontent.com/98538479/151635812-2c0e213a-a760-41b1-8580-2fc7930963a6.PNG)

**Comment by steve-lad** [comment]
Notes for posterity: This is actually a freePBX issue - its author describes the approach as insanity!
When editing a device(extension), freePBX first deletes it and then adds it. It never signifies the context of the delete to the class. 
As a result the associated line linkages are deleted, but not recreated - Sccp_manager is subservient to freePBX!
Will file an issue with Sangoma, and look at kludges to workaround that do not pollute the db.

**Comment by ghost** [comment]
So it can't be fixed :(
let's hope for good events

**Comment by steve-lad** [comment]
Implement delete via destructor
