### ISSUE TITLE
Line settings are included in add device and therefore ignored - need to move these settings to line

### ISSUE THREAD

**Issue by ghost** [chan-sccp/sccp_manager#69]
it is logical to assume that when you add a new device, it takes some device settings from the server configuration. Such as for example:
Message Lamp On Call 
Call history stored book
Call Forward
Transfer
Call Forward busy
Call Forward NO ANSWER
DND Button on Device 

Or the same thing with lines, the server configuration specifies some parameters, and when creating a line, it does not take values from the server configuration:
Directed Pickup Answer in the server configuration, it is "No", and when creating a line (extension), it is "Yes"
Directed Pickup the same thing

either remove these parameters from the server configuration or fix it so that the settings are loaded
And if you fix it, it would be super to increase the values of the server configuration, which were then loaded when creating a line or device

**Comment by steve-lad** [comment]
Thanks for your comments - sections are clearly outlined and new devices do inherit the server settings, which in turn, inherit chan-sccp defaults.

Device(hardware) settings are different from line (extension) settings - the examples that you list are all line settings and therefore not inherited by devices.

**Comment by ghost** [comment]
No, not everyone inherits. you reject the facts, so I don't need to create topics, since you just close them.

**Comment by steve-lad** [comment]
Put simply, you cannot inherit what you do not own. I am reopening this issue because these settings are in the wrong place and therefore misleading. This is a legacy issue. They will be moved to line settings.

**Comment by ghost** [comment]
at the moment I'm installing a new freepbx and will install sccp_manager again to show on the video, since you don't believe me :)

**Comment by steve-lad** [comment]
You are not reading, and understandably perhaps, do not understand the complex data structure of chan-sccp. Put simply, these buttons will disappear in add device - They have no meaning!

**Comment by ghost** [comment]
not "perhaps". I definitely don't understand)
