### ISSUE TITLE
Call Transfer Issue

### ISSUE THREAD

**Issue by cagriaksu** [chan-sccp/sccp_manager#71]
Hello,

When I try to transfer a call by pressing the transfer soft button "Key is Not Active" is displayed on the screen.

I tried re-compiling from source with --enabled-advaned-functions, but to avail, still getting the same result on both a 7962 and 7975.

**Comment by dkgroot** [comment]
Sorry guys, i did not notice this issue ticket for a while, only to find out it's a freepbx/sccp_manager question/issue. I transferred it here. Looks like @waffle-stomper might have already provided the solution on how to make it work, so maybe the ticket can already be closed.

**Comment by steve-lad** [comment]
As pointed out by Waffle-stomper, for this softkey to work in chan-sccp, transfer must be enabled.

The Sccp_manager setting (which is in SCCP Connectivity > Phones Manager > [Edit Extension] > Sccp ) is correctly saved in the current version.

This issue should be closed after verification.
