### ISSUE TITLE
collation is not in sync

### ISSUE THREAD

**Issue by tomquinn04** [chan-sccp/sccp_manager#9]
Error when opening the phone manager page:

```
QLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '='
File:/var/www/html/admin/modules/sccp_manager/sccpManClasses/dbinterface.class.php:150
```

(@dkgroot knows about this)

**Comment by steve-lad** [comment]
@tomquinn04 Assuming that you can connect to your database, could you post the output of

SHOW TABLE STATUS WHERE NAME LIKE 'sccp%';

and add the result here

**Comment by tomquinn04** [comment]
```
MariaDB [asterisk]> SHOW TABLE STATUS WHERE NAME LIKE 'sccp%';
#+------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+--------------------+----------+----------------+-------------------------------------------------------------------------------------------------------------+
| Name             | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time         | Check_time          | Collation          | Checksum | Create_options | Comment                                                                                                     |
+------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+--------------------+----------+----------------+-------------------------------------------------------------------------------------------------------------+
| sccpbuttonconfig | MyISAM |      10 | Dynamic    |    0 |              0 |           0 | 281474976710655 |         1024 |         0 |           NULL | 2021-06-06 14:12:30 | 2021-06-06 14:12:30 | 2021-06-06 14:12:30 | utf8_general_ci    |     NULL |                |                                                                                                             |
| sccpdevice       | InnoDB |      10 | Compact    |    1 |          16384 |       16384 |               0 |            0 |  15728640 |           NULL | 2021-06-06 14:12:30 | NULL                | NULL                | utf8mb4_unicode_ci |     NULL |                |                                                                                                             |
| sccpdeviceconfig | NULL   |    NULL | NULL       | NULL |           NULL |        NULL |            NULL |         NULL |      NULL |           NULL | NULL                | NULL                | NULL                | NULL               |     NULL | NULL           | Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_unicode_ci,IMPLICIT) for operation '=' |
| sccpdevmodel     | InnoDB |      10 | Compact    |  126 |            130 |       16384 |               0 |        16384 |  15728640 |           NULL | 2021-06-06 14:12:29 | NULL                | NULL                | utf8mb4_unicode_ci |     NULL |                |                                                                                                             |
| sccpline         | InnoDB |      10 | Compact    |    1 |          16384 |       16384 |               0 |        16384 |  15728640 |              2 | 2021-06-06 14:12:30 | NULL                | NULL                | utf8mb4_unicode_ci |     NULL |                |                                                                                                             |
| sccpsettings     | InnoDB |      10 | Compact    |   33 |            496 |       16384 |               0 |            0 |  15728640 |           NULL | 2021-06-06 13:07:30 | NULL                | NULL                | utf8mb4_unicode_ci |     NULL |                |                                                                                                             |
| sccpuser         | MyISAM |      10 | Dynamic    |    0 |              0 |           0 | 281474976710655 |         1024 |         0 |           NULL | 2021-06-06 12:34:18 | 2021-06-06 12:34:18 | NULL                | utf8_general_ci    |     NULL |                |                                                                                                             |
+------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+---------------------+---------------------+--------------------+----------+----------------+-------------------------------------------------------------------------------------------------------------+
7 rows in set, 1 warning (0.02 sec)

MariaDB [asterisk]> #
```

@steve-lad

**Comment by steve-lad** [comment]
@tomquinn04

[edited to correct backup for MariaDb]
I am not sure how you arrived there.....but to fix I suggest the following steps. You need to add file path to somewhere that you will remember in step 1. Execute step by step rather than as a single transaction.

_In the shell, create a backup_
1. mysqldump -p asterisk > 'filepath'

_login to the database_
1. USE asterisk;
2. ALTER TABLE sccpbuttonconfig ENGINE = InnoDB;
3. ALTER TABLE sccpuser ENGINE = InnoDB;
4. DROP VIEW sccpdeviceconfig;
5. ALTER TABLE sccpbuttonconfig CONVERT TO character set utf8mb4 collate utf8mb4_unicode_ci;
6. ALTER TABLE sccpuser CONVERT TO character set utf8mb4 collate utf8mb4_unicode_ci;

Once you have done that, and assuming no errors:

7.  in FreePbx Admin -> Module Admin, uninstall Sccp_Manager. 
(Ignore the error message)
8. In FreePbx Admin -> Module Admin, install Sccp Manager.

That should fix your issue.

**Comment by tomquinn04** [comment]
is step 1 a command, or do you just mean go into `mysql asterisk` @steve-lad

**Comment by steve-lad** [comment]
Its a command - make sure that you are connected to the right database!

**Comment by tomquinn04** [comment]
@steve-lad

**Comment by tomquinn04** [comment]
oh

**Comment by tomquinn04** [comment]
i am bad at github.. hehe

```
MariaDB [asterisk]> BACKUP DATABASE asterisk TO DISK = '/root/dbbackupjune21';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BACKUP DATABASE asterisk TO DISK = '/root/dbbackupjune21'' at line 1
```
getting an error in step 2 @steve-lad

**Comment by steve-lad** [comment]
@tomquinn04
exit mysql;

in the shell,

 mysqldump -p asterisk > 'filepath'

Then log into the database, and proceed from step 3

**Comment by steve-lad** [comment]
@tomquinn04

I have revised the steps, so deleted the intermediate so that other users who find this see a clear answer.
Please close the issue when all is good - This is not an Sccp_Manager issue.

**Comment by steve-lad** [comment]
This issue will be seen if the following conditions are met:

Using old version of MariaDB (build 5 as is included in some distros)
First time use of Sccp_Manger;
Install older versions of Develop branch;   (DOES not apply to current Develop)
Install fails at Database Creation;
Install Stable;

Cause
Develop uses different collation than Stable (Develop uses FreePBX defaults)

Workarounds:
Follow steps outlined in earlier post
Install current Develop.

**Comment by mikeSerg** [comment]
> 


it didn't work for me (freepbx 16 distro with Asterisk 18)
### (problem solving below)

sccp_chan was installed by this steps:


1)
yum update -y
yum upgrade -y
yum install git asterisk-devel -y
cd /usr/src
git clone https://github.com/chan-sccp/chan-sccp chan-sccp
cd chan-sccp
./configure --enable-conference --enable-advanced-functions --enable-distributed-devicestate
make -j2 && make install

2)
nano /etc/asterisk/modules.conf and inserting:

noload = chan_skinny.so
load = chan_sccp.so


3)
yum install tftp tftp-server* xinetd* -y


nano /etc/xinetd.d/tftp

service tftp
{
    id              = tftp
    socket_type     = dgram
    protocol        = udp
    user            = root
    wait            = no
    disable         = no
    server          = /usr/sbin/in.tftpd
    server_args     = /tftpboot
    FLAGS           = IPv6 IPv4
}


systemctl restart xinetd


fwconsole restart

4)
mysql  asterisk < /usr/src/chan-sccp/conf/mysql-v5_enum.sql

5) Install chan_sccp manager via GUI , from this link
https://github.com/chan-sccp/sccp_manager/releases/tag/v14.5.0.4

### **SOLUTION!, wich works for me:**

before create tables from /usr/src/chan-sccp/conf/mysql-v5_enum.sql (STEP 4)
needs edit /usr/src/chan-sccp/conf/mysql-v5_enum.sql file 

replace all lines in this file,which content, 
ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8mb4_general_ci; 

to

ENGINE=INNODB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;


and now, create tables in asterisk database
mysql  asterisk < /usr/src/chan-sccp/conf/mysql-v5_enum.sql

**Comment by paulius-bulotas** [comment]
SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '='
File:/var/www/html/admin/modules/sccp_manager/sccpManClasses/dbinterface.class.php:171

> @tomquinn04
> 
> [edited to correct backup for MariaDb] I am not sure how you arrived there.....but to fix I suggest the following steps. You need to add file path to somewhere that you will remember in step 1. Execute step by step rather than as a single transaction.
> 
> _In the shell, create a backup_
> 
> 1. mysqldump -p asterisk > 'filepath'
> 
> _login to the database_
> 
> 1. USE asterisk;
> 2. ALTER TABLE sccpbuttonconfig ENGINE = InnoDB;
> 3. ALTER TABLE sccpuser ENGINE = InnoDB;
> 4. DROP VIEW sccpdeviceconfig;
> 5. ALTER TABLE sccpbuttonconfig CONVERT TO character set utf8mb4 collate utf8mb4_unicode_ci;
> 6. ALTER TABLE sccpuser CONVERT TO character set utf8mb4 collate utf8mb4_unicode_ci;
> 
> Once you have done that, and assuming no errors:
> 
> 7. in FreePbx Admin -> Module Admin, uninstall Sccp_Manager.
>    (Ignore the error message)
> 8. In FreePbx Admin -> Module Admin, install Sccp Manager.
> 
> That should fix your issue.

still same issue help me

tried and that 



> > 
> 
> it didn't work for me (freepbx 16 distro with Asterisk 18)
> 
> ### (problem solving below)
> sccp_chan was installed by this steps:
> 
> 
> yum update -y yum upgrade -y yum install git asterisk-devel -y cd /usr/src git clone https://github.com/chan-sccp/chan-sccp chan-sccp cd chan-sccp ./configure --enable-conference --enable-advanced-functions --enable-distributed-devicestate make -j2 && make install
> 
> 
> nano /etc/asterisk/modules.conf and inserting:
> 
> noload = chan_skinny.so load = chan_sccp.so
> 
> 
> yum install tftp tftp-server* xinetd* -y
> 
> nano /etc/xinetd.d/tftp
> 
> service tftp { id = tftp socket_type = dgram protocol = udp user = root wait = no disable = no server = /usr/sbin/in.tftpd server_args = /tftpboot FLAGS = IPv6 IPv4 }
> 
> systemctl restart xinetd
> 
> fwconsole restart
> 
> 
> mysql asterisk < /usr/src/chan-sccp/conf/mysql-v5_enum.sql
> 
> 5. Install chan_sccp manager via GUI , from this link
>    https://github.com/chan-sccp/sccp_manager/releases/tag/v14.5.0.4
> 
> ### **SOLUTION!, wich works for me:**
> before create tables from /usr/src/chan-sccp/conf/mysql-v5_enum.sql (STEP 4) needs edit /usr/src/chan-sccp/conf/mysql-v5_enum.sql file
> 
> replace all lines in this file,which content, ENGINE=INNODB DEFAULT CHARACTER SET utf8 COLLATE utf8mb4_general_ci;
> 
> to
> 
> ENGINE=INNODB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
> 
> and now, create tables in asterisk database mysql asterisk < /usr/src/chan-sccp/conf/mysql-v5_enum.sql

but still same problem please help me.
